enum ActionTypes {
  REQUEST_STARTED = 'REQUEST_STARTED',
  REQUEST_SUCCEEDED = 'REQUEST_SUCCEEDED',
  REQUEST_FAILED = 'REQUEST_FAILED',
  CLEAR_REQUEST_FAILED = 'CLEAR_REQUEST_FAILED',
  LOAD_HTML_CONTENT = 'LOAD_HTML_CONTENT',
  LOAD_XML_CONTENT = 'LOAD_XML_CONTENT',
  SET_CONTENT = 'SET_CONTENT',
}

export default ActionTypes;
